### ISSUE TITLE
Instance ends, API connections not

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#17]
when an instance exits, established connections to its API remain established

**Comment by MichalCz** [comment]
@patuwwy as I understand this is now corrected with a timeout of 10 secs?

**Comment by alicja-gruzdz** [comment]
@patuwwy will reply, but my understanding was the timeout fix is a delay of closing an Instance Controller.
I'm not sure the issue mentioned here was not addressed in https://github.com/scramjetorg/transform-hub/pull/7 (even though this issue was opened a bit later). Covered by BDD test https://github.com/scramjetorg/transform-hub/blob/release/0.12/bdd/features/e2e/E2E-010-cli.feature#L183 Maybe @luccam-scr can clarify.

**Comment by patuwwy** [comment]
@MichalCz 
IMO it is about remaining active connections to instance endpoints, for example: You are sending data to /input, instance end and your POST request remains active

**Comment by MichalCz** [comment]
Ah, ok. It should get disconnected indeed. Ok, so tech debt - let's fix it in the next cleaning sprint.

**Comment by MichalCz** [comment]
This is still occuring, I noted that in my last tests with input/output. If the sequence crashes or is closed all API calls should be closed. I think the best solution would be to add this on `lookup` in `api-server`.

**Comment by patuwwy** [comment]
```
22:47 $  si seq deploy packages/endless-names-output.tar.gz --args [10] && si inst output - 
SequenceClient {
  _id: '47fcc5e4-e312-4997-8062-49fa80824936',
  host: HostClient {
    apiBase: 'http://127.0.0.1:8000/api/v1',
    client: ClientUtils {
      apiBase: 'http://127.0.0.1:8000/api/v1',
      fetch: [Function (anonymous)],
      normalizeUrlFn: [Function: normalizeUrl]
    }
  },
  sequenceURL: 'sequence/47fcc5e4-e312-4997-8062-49fa80824936'
}
InstanceClient {
  host: HostClient {
    apiBase: 'http://127.0.0.1:8000/api/v1',
    client: ClientUtils {
      apiBase: 'http://127.0.0.1:8000/api/v1',
      fetch: [Function (anonymous)],
      normalizeUrlFn: [Function: normalizeUrl]
    }
  },
  _id: 'a8a80e46-e397-404a-8bae-a3a59c8bb588',
  instanceURL: 'instance/a8a80e46-e397-404a-8bae-a3a59c8bb588'
}
{"name":"Alice"}
{"name":"Ada"}
{"name":"Aga"}
{"name":"Michał"}
{"name":"Patryk"}
{"name":"Rafał"}
{"name":"Aida"}
{"name":"Basia"}
{"name":"Natalia"}
{"name":"Monika"}
{"name":"Wojtek"}
22:55 $ 
```

**Comment by MichalCz** [comment]
Seems like it works?

**Comment by alicja-gruzdz** [comment]
I confirm what @patuwwy demonstrated still works. Closing the issue.

```
 $ si seq deploy endless-names-output.tar.gz --args [10] && si inst output - 
{"_id":"eb06cec6-62b4-4bbb-868f-22264beb14b0","host":{"apiBase":"http://127.0.0.1:8000/api/v1","client":{"apiBase":"http://127.0.0.1:8000/api/v1"}},"sequenceURL":"sequence/eb06cec6-62b4-4bbb-868f-22264beb14b0"}
{"host":{"apiBase":"http://127.0.0.1:8000/api/v1","client":{"apiBase":"http://127.0.0.1:8000/api/v1"}},"_id":"4788c098-2713-49df-83aa-66a3d7f7fe79","instanceURL":"instance/4788c098-2713-49df-83aa-66a3d7f7fe79"}
{"name":"Alice"}
{"name":"Ada"}
{"name":"Aga"}
{"name":"Michał"}
{"name":"Patryk"}
{"name":"Rafał"}
{"name":"Aida"}
{"name":"Basia"}
{"name":"Natalia"}
{"name":"Monika"}
{"name":"Wojtek"}
(base) alis@arch:~$ 

```
